name: lambda-interpreter
version: 0.1.0.0
github: "githubuser/lambda-interpreter"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2020 Author name here"

extra-source-files:
  - README.adoc
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/lambda-interpreter#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - unix
  - ansi-terminal
  - hspec
  - hspec-discover
  - QuickCheck

library:
  source-dirs: src

executables:
  lambda-interpreter-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-interpreter

tests:
  lambda-interpreter-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-interpreter
