= Haskell CLI λ-calculus interpreter
:toc:
:stem: latexmath

Implement λ-calculus interpreter supporting:

. loading of λ-expressions by user,
. order of evaluation step by step (application of one reduction)

Interpreter has to understand basics of λ-calcul:

* encapsulation, abstraction, application
* free and bound variables
* beta reduction
* eta reduction
* normal order reduction and normal form (no further reductions possible)

It has to be able to solve at least factorial of 5 or similiarly difficult expression (`++ Y (λfn. zero n 1 (* n f (- n 1))) 5 ++`).
Support interpreting step-by-step (one application of reduction) and expansion of symbolic names  (`zero`, `Y`, `1`, ...).

Implement CLI:

* starting up cli will open enviroment for user input,
* each line either assignment of expression to symbolic name or application

Example:

```
user@pc > lci
> 1 = (λs.(λz. (s z)))
> 1
(λs.(λz. (s z)))
> add = (λx.(λy.(λs.(λz. x s (y s z)))))
> add 1 1
(λx.(λy.(λs.(λz. x s (y s z))))) (λs.(λz. (s z))) (λs.(λz. (s z)))
(λy.(λs.(λz. (λs.(λz. (s z))) s (y s z)))) (λs.(λz. (s z)))
(λs.(λz. (λs.(λz. (s z))) s ((λs.(λz. (s z))) s z))
...
(λs.(λz. (s (s z))))
```