= Haskell CLI 位-calculus interpreter
:toc:
:stem: latexmath

== Task

Implement 位-calculus interpreter supporting:

. loading of 位-expressions by user,
. order of evaluation step by step (application of one reduction)

Interpreter has to understand basics of 位-calcul:

* encapsulation, abstraction, application
* free and bound variables
* beta reduction
* alpha conversion
* normal order reduction and normal form (no further reductions possible)

It has to be able to solve at least factorial of 5 or similiarly difficult expression (`Y (\\f n. ZERO n 1 (* n f (- n 1))) 5`).
Support interpreting step-by-step (one application of reduction) and expansion of symbolic names  (`ZERO`, `Y`, `1`, ...).

Implement CLI:

* starting up cli will open enviroment for user input,
* each line either assignment of expression to symbolic name or application

== Syntax

* Use \ and . to symbolize abstraction - `(\x.x)`
** Wrongly typed expressions will throw errors
** Abstraction support multiple arguments - `(\x y.x y)`, they have to be separated by whitespace
* There are some basic defined macros - `+, -, *, ^, TRUE, FALSE, Y, FAC, ...`
** Accessing non defined macros will throw errors
** User can define 'macros' on runtime - `X = 1`
** There are defined number macros up to 120
** Macros have defined special equality - `(\x.x) == `(\y.y)`, names are ignored and only structure is used, this helps with evaluation of result of `^` operator
* Variables have to start with lowercase letter, other expressions are identified as macrosv
* Program supports quiet and normal mode
** Normal - every step is written down and user has to step manually
** Quiet - program writes down only answer

== Example

```
stack exec -- lambda-interpreter-exe
> + 1 1
((\x y s z.x s (y s z)) 1 1)
((\y s z.1 s (y s z)) 1)
((\s z.1 s (1 s z)))
((\s z.(\s z.s z) s (1 s z)))
((\s z.(\z.s z) (1 s z)))
((\s z.s (1 s z)))
((\s z.s ((\s z.s z) s z)))
((\s z.s ((\z.s z) z)))
((\s z.s (s z)))
< 2
> ADD1 = + 1
((\x y s z.x s (y s z)) 1)
((\y s z.1 s (y s z)))
((\y s z.(\s z.s z) s (y s z)))
((\y s z.(\z.s z) (y s z)))
((\y s z.s (y s z)))
< SUCC
> ADD1 2
(+ 1 2)
((\x y s z.x s (y s z)) 1 2)
...
((\s z.s (s (s z))))
< 3
Ctrl+C

stack exec -- lambda-interpreter-exe -q
> + 23 12
< 35
> - 76 34
< 42
> * 12 5
< 60
> ^ 2 6
< 64
> Y FAC 4
< 24
> + X 1
Error: Can't find macro - X
> X = 2
< 2
> + X 2
< 4
> (+ 1
Error: Mismatching brackets
> X = + 1 1=
Error: Incorrect assignment
```